### ISSUE TITLE
覆盖图片上传， 原先访问的url不能得到最新的图片？ ，通过随机url却可以(V7)

### ISSUE THREAD

**Issue by acf77** [qiniu/api.v7#117]
有什么办法让他及时更新显示最新的图片吗？（浏览器无痕模式下）

**Comment by KevinChenQiniu** [comment]
需要覆盖上传后主动提交刷新请求
https://developer.qiniu.com/fusion/kb/1325/refresh-the-cache-and-the-effect-of-time
