### ISSUE TITLE
MakePublicURL 应先清除 domain 的末尾斜线再拼接

### ISSUE THREAD

**Issue by wxdao** [qiniu/api.v7#119]
不然 `storage.MakePublicURL("http://a.b.c/", "hi.jpg")` 会返回 `http://a.b.c//hi.jpg`，同时影响 `storage.MakePrivateURL` 签名的计算，导致鉴权错误

**Comment by jemygraw** [comment]
传入domain的时候可以不带斜杠，自己处理下吧。

**Comment by wxdao** [comment]
什么叫“可以不带斜杠”？带斜杠后计算结果就是错的了用不了！

**Comment by jemygraw** [comment]
就是你域名传入的时候不带斜杠。

**Comment by wspl** [comment]
![image](https://user-images.githubusercontent.com/2133311/36461327-c4cfb658-16f7-11e8-96c4-1134c3431ff7.png)
只能说你们七牛的 Go 程序员真的不咋地，培训班出来的？

**Comment by jemygraw** [comment]
@wspl we will fix it soon.
