### ISSUE TITLE
Post http://up.qiniup.com: EOF

### ISSUE THREAD

**Issue by AnnatarHe** [qiniu/api.v7#122]
您好，同样的代码，在半个月前是正常能用的。
在今天(2018-01-06 23:15) 几乎无法保存数据。报错为：

```text
Post http://up.qiniup.com: EOF
```

今天测试发了约 200 个请求。成功了 27 个。

希望有空能帮忙查看一下。

代码里是并发16个请求的，不知是否有影响。

谢谢。

**Comment by AnnatarHe** [comment]
应该是服务器原因。一月七号已可用

**Comment by helloyou2012** [comment]
带宽低的环境下分片上传还是会有这个问题，测试环境：

```
上行带宽：1M bps
文件大小：160M
```

**Comment by techone577** [comment]
确实低带宽下也会有相同的问题
