### ISSUE TITLE
VerifyCallback for api.v7

### ISSUE THREAD

**Issue by xushiwei** [qiniu/api.v7#13]
@xuzhaokui

**Comment by vasth** [comment]
请加一下VerifyCallback 方法
因为没有 VerifyCallback 方法，我根据 v6  写成这样的方法 可是获取的token为空，err为 EOF
func VerifyCallback(req *http.Request) (bool, error) {
	var mac = qbox.NewMac(" *********************", "*************************** ") 
	auth := req.Header.Get("Authorization") 
	if auth == "" {
		return false, nil
	}

	token, err := mac.SignRequest(req, true) 
	if err != nil {
		return false, err
	}

	return auth == "QBox "+token, nil
}

**Comment by xuzhaokui** [comment]
https://github.com/qiniu/api.v7/pull/24
