### ISSUE TITLE
bucketManager.Fetch 中使用 returnBody 魔法变量

### ISSUE THREAD

**Issue by suconghou** [qiniu/api.v7#143]
类似于`formUploader.PutWithoutKey` 在 bucketManager.Fetch 中自定义返回的数据,比如 imageInfo 和 exif 信息

**Comment by forrest-mao** [comment]
目前七牛的存储接口确实还不支持 fetch 操作抓取远程链接后返回其他文件的信息，建议可以在抓取完成后，单独通过 https://developer.qiniu.com/dora/api/1269/pictures-basic-information-imageinfo 和 https://developer.qiniu.com/dora/api/1260/photo-exif-information-exif 来获取图片的属性信息
