### ISSUE TITLE
接口看起来不全？

### ISSUE THREAD

**Issue by qiqizjl** [qiniu/api.v7#146]
尝试将CDN通过API接入 但是发现代码中对接的CDN接口不全

比如说缺少``获取域名列表``等等~。

请问这个接口是遗漏了呢还是需要自己用通用的方法接入

**Comment by forrest-mao** [comment]
内部 issue：TS-1003

**Comment by Mei-Zhao** [comment]
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
该issue会在go-sdk中解决
