### ISSUE TITLE
go get -u github.com/qiniu/api.v7 failed!! 没有下载成功 无法引用

### ISSUE THREAD

**Issue by unionTime** [qiniu/api.v7#148]
platform:MacOS 12
go version: go1.11 darwin/amd64

error message:
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

can you give me some ideas? thanks~

**Comment by unixcx** [comment]
```
$ mkdir -p $GOPATH/src/golang.org/x/
$ cd $GOPATH/src/golang.org/x
$ git clone git clone https://github.com/golang/net.git net
$ go install net
```

**Comment by forrest-mao** [comment]
内部issue ：TS-1004

**Comment by Mei-Zhao** [comment]
是否尝试使用https://goproxy.io/zh/
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
如有问题，可以在go-sdk中重新提issue解决
