### ISSUE TITLE
请去掉 qiniupkg.com/x 的依赖

### ISSUE THREAD

**Issue by hyacinthus** [qiniu/api.v7#154]
虽然这个包的依赖改成了github下的，
但是 github.com/qiniu/x 还是会依赖 qiniupkg

在境外构建大概会有三分之一因为 qiniupkg.com timeout 失败。

不改也可以，把 qiniupkg.com 加个全球cdn也行啊，你们自己都有cdn业务。

**Comment by astimes** [comment]
+1

**Comment by mickyss** [comment]
无耐

**Comment by mickyss** [comment]
无奈 隔壁老哥的
$ mkdir -p $GOPATH/src/golang.org/x/
$ cd $GOPATH/src/golang.org/x
$ git clone git clone https://github.com/golang/net.git net
$ go install net

可行，

**Comment by hyacinthus** [comment]
> 无奈 隔壁老哥的
> $ mkdir -p $GOPATH/src/golang.org/x/
> $ cd $GOPATH/src/golang.org/x
> $ git clone git clone https://github.com/golang/net.git net
> $ go install net
> 
> 可行，

我们是在讨论国外访问七牛国内服务器不稳定的问题

**Comment by wangsongyan** [comment]
+1

**Comment by micanzhang** [comment]
+1 

qiniupkg.com/x  和 github.com/qiniu/x  相同的代码，但是不同的包名，能否改为只依赖其中一个

**Comment by rebootok** [comment]
+1

**Comment by forrest-mao** [comment]
#148

**Comment by Mei-Zhao** [comment]
是否尝试使用https://goproxy.io/zh/
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
如有问题，可以在go-sdk中重新提issue解决
