### ISSUE TITLE
docker  unrecognized import path "golang.org/x/net/context"

### ISSUE THREAD

**Issue by ZQCard** [qiniu/api.v7#158]
我的 dockerfile
FROM golang:latest

MAINTAINER Card "445864742@qq.com"

WORKDIR $GOPATH/src/resource-backend
ADD . $GOPATH/src/resource-backend
#七牛云特殊处理
RUN mkdir -p $GOPATH/src/golang.org/x/
RUN cd $GOPATH/src/golang.org/x
RUN git clone https://github.com/golang/net.git net
RUN go get github.com/qiniu/api.v7/auth/qbox
RUN go get github.com/qiniu/api.v7/storage

错误信息：
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:443: connect: connection timed out)

在服务器单机执行是可以的，docker不行,真的是因为请求超时吗

**Comment by ZQCard** [comment]
改用了 govendor

**Comment by forrest-mao** [comment]
#148

**Comment by Mei-Zhao** [comment]
是否尝试使用https://goproxy.io/zh/
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
如有问题，可以在go-sdk中重新提issue解决
