### ISSUE TITLE
api 建议

### ISSUE THREAD

**Issue by oilbeater** [qiniu/api.v7#16]
对象下载的操作应该也由 bucket 来承担，不应该直接调用 http，会造成使用理解上的混乱。很多细节性的操作比如range，断点续传类的功能还需要去查 http 的api。可以参考 s3 的 get 相关 api ，设计的还是比较人性化。

创建连接部分的配置需要有些文档说明，至今不明白IoHost,rshost 还有 rsfhost 是干什么的，

**Comment by longbai** [comment]
*  上传和下载是两回事情,下载就是普通的http 资源，通过URL 定位。下载以后也会推出sdk。
*  这些host是内部的服务器标识，您只要关心bucket manager 的API 就行，内部的服务器基本不会变

**Comment by oilbeater** [comment]
@longbai 我想用的是海外的上传点，zone 里面现在没有需要自定义 config 然后我就糊涂了，不知道除了 uphost 其他的要怎么弄

**Comment by longbai** [comment]
uphost 是有海外cdn 加速，其他的没有，不用变

**Comment by oilbeater** [comment]
Thanks, 建议加一个海外上传的 zone 吧
