### ISSUE TITLE
ListBucket: source: timeout awaiting response headers

### ISSUE THREAD

**Issue by m198799** [qiniu/api.v7#170]
长时间请求接口会导致大量报错

ListBucket: source: timeout awaiting response headers

**Comment by forrest-mao** [comment]
一般列取超时是因为空间存在大量文件的删除，会容易出现类似问题，目前相关问题已经做了优化，您看是否方便
1. 使用的接口通过 https://github.com/qiniu/api.v7/blob/master/storage/bucket.go#L494 ListBucket 接口再做尝试
2. 针对列取文件使用尽可能具体的前缀来列取，这样对列取的效果会有明显的改善

**Comment by Mei-Zhao** [comment]
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
有疑问可以在go-sdk中继续提出issue
