### ISSUE TITLE
Cannot find module github/qiniu/x/bytes

### ISSUE THREAD

**Issue by clearloop** [qiniu/api.v7#172]
### go version
```
 𝝺 go version
go version go1.13 darwin/amd64
```

## logs
```
 𝝺 go get -u github.com/qiniu/api.v7
go: finding github.com/qiniu/x v8.0.0+incompatible
go: finding golang.org/x/net latest
../../../../../pkg/mod/github.com/qiniu/api.v7@v7.2.5+incompatible/storage/resume_base.go:13:2: cannot find module providing package github.com/qiniu/x/bytes.v7
../../../../../pkg/mod/github.com/qiniu/api.v7@v7.2.5+incompatible/auth/qbox/qbox_auth.go:12:2: cannot find module providing package github.com/qiniu/x/bytes.v7/seekable
../../../../../pkg/mod/github.com/qiniu/api.v7@v7.2.5+incompatible/storage/rpc.go:13:2: cannot find module providing package github.com/qiniu/x/reqid.v7
../../../../../pkg/mod/github.com/qiniu/api.v7@v7.2.5+incompatible/storage/resume_base.go:14:2: cannot find module providing package github.com/qiniu/x/xlog.v7
```

## Addition

Just saw that `qiniu/x` upgraded to v8.0.0, if the problem caused by the upgrading? or I've missed some steps?

**Comment by sun-wenming** [comment]
头大。用不了。
```
go: finding github.com/qiniu/x v8.0.0+incompatible
go build github.com/qiniu/x/bytes.v7/seekable: no Go files in
go build github.com/qiniu/x/bytes.v7: no Go files in
go build github.com/qiniu/x/reqid.v7: no Go files in
go build github.com/qiniu/x/xlog.v7: no Go files in

```

**Comment by sun-wenming** [comment]
私有包，不能用代理。 直接  go get 我是这样解决的。

**Comment by clearloop** [comment]
这边同时清掉 `$GOPATH/mod/github.com/qiniu` 与 `$GOPATH/src/github.com/qiniu` 还是一样的问题，专门起了个 flask 上传图片...头晕

@sun-wenming

**Comment by sun-wenming** [comment]
其他的包可以正常下载吗？
比如：`go get github.com/sun-wenming/go-tools@v0.6.5`
你可以试试把自己现有公共仓库改成私有的，看看还可以正常拉下来包不可以了。

**Comment by clearloop** [comment]
这个库可以拉下来， bro

```
 𝝺 go get github.com/sun-wenming/go-tools@v0.6.5
go: finding github.com/sun-wenming v0.6.5
go: finding github.com/sun-wenming/go-tools v0.6.5
go: finding github.com v0.6.5
go: downloading github.com/sun-wenming/go-tools v0.6.5
go: extracting github.com/sun-wenming/go-tools v0.6.5
go get github.com/sun-wenming/go-tools@v0.6.5: github.com/sun-wenming@v0.6.5: unexpected end of JSON input
 𝝺 
```

**Comment by 52lemon** [comment]
使用go mod tidy 提示报错

`
E:\GolandProjects\iris_demo>go mod tidy
go: finding github.com/qiniu/x v8.0.0+incompatible
iris_demo/libs imports
        github.com/qiniu/api.v7/auth/qbox imports
        github.com/qiniu/x/bytes.v7/seekable: cannot find module providing package github.com/qiniu/x/bytes.v7/seekable
iris_demo/libs imports
        github.com/qiniu/api.v7/storage imports
        github.com/qiniu/x/bytes.v7: cannot find module providing package github.com/qiniu/x/bytes.v7
iris_demo/libs imports
        github.com/qiniu/api.v7/storage imports
        github.com/qiniu/x/reqid.v7: cannot find module providing package github.com/qiniu/x/reqid.v7
iris_demo/libs imports
        github.com/qiniu/api.v7/storage imports
        github.com/qiniu/x/xlog.v7: cannot find module providing package github.com/qiniu/x/xlog.v7

`
