### ISSUE TITLE
cannot load github.com/qiniu/x/bytes.v7: cannot find module providing package github.com/qiniu/x/bytes.v7

### ISSUE THREAD

**Issue by macnie** [qiniu/api.v7#174]
什么鬼！直接不能用了！

**Comment by CarlJi** [comment]
最新的代码已经移除了对"github.com/qiniu/x"的依赖，建议您这边更新下代码。

**Comment by macnie** [comment]
怎么更新？ 
 
------------------ 原始邮件 ------------------
发件人: "Changjun Ji"; 
发送时间: 2019年9月16日(星期一) 晚上9:12
收件人: "qiniu/api.v7"; 
抄送: "东林"; "Author"; 
主题: Re: [qiniu/api.v7] cannot load github.com/qiniu/x/bytes.v7: cannot find module providing package github.com/qiniu/x/bytes.v7 (#174)

 

最新的代码已经移除了对"github.com/qiniu/x"的依赖，建议您这边更新下代码。

**Comment by CarlJi** [comment]
在您的项目中，拉取最新的api.v7库中的代码。

**Comment by macnie** [comment]
我使用了 require github.com/qiniu/api.v7 latest

然后go build 出现：


go: finding github.com/qiniu/x v8.0.0+incompatible
build gblog: cannot load github.com/qiniu/x/bytes.v7: cannot find module providing package github.com
/qiniu/x/bytes.v7



我拉取得已经是最新的了



 
 
------------------ 原始邮件 ------------------
发件人: "Changjun Ji"; 
发送时间: 2019年9月16日(星期一) 晚上9:15
收件人: "qiniu/api.v7"; 
抄送: "东林"; "Author"; 
主题: Re: [qiniu/api.v7] cannot load github.com/qiniu/x/bytes.v7: cannot find module providing package github.com/qiniu/x/bytes.v7 (#174)

 

在您的项目中，拉取最新的api.v7库中的代码。

**Comment by CarlJi** [comment]
建议执行go get -u github.com/qiniu/api.v7 试试呢

**Comment by li-caspar** [comment]
新项目，直接执行go get -u github.com/qiniu/api.v7  然后出现了
go: finding github.com/qiniu/api.v7 v7.2.5+incompatible
go: downloading github.com/qiniu/api.v7 v7.2.5+incompatible
go: extracting github.com/qiniu/api.v7 v7.2.5+incompatible
go: finding github.com/qiniu/x v8.0.0+incompatible
go build github.com/qiniu/x/bytes.v7/seekable: no Go files in
go build github.com/qiniu/x/bytes.v7: no Go files in
go build github.com/qiniu/x/reqid.v7: no Go files in
go build github.com/qiniu/x/xlog.v7: no Go files in

**Comment by li-caspar** [comment]
可能不知道怎么了，拉的是github.com/qiniu/api.v7 v7.2.5 ， 当我拉取指定版本时报错
go get github.com/qiniu/api.v7@v7.3.0

go: finding github.com/qiniu/api.v7 v7.3.0
go: finding github.com/qiniu v7.3.0
go: finding github.com v7.3.0
go get github.com/qiniu/api.v7@v7.3.0: unexpected status (https://goproxy.cn/github.com/qiniu/api.v7/@v/v7.3.0.info): 404 Not Found

**Comment by bachue** [comment]
@li-caspar 你的 proxy 没同步最新的版本吧。

**Comment by li-caspar** [comment]
> @li-caspar 你的 proxy 没同步最新的版本吧。

我用的代理是https://goproxy.cn ,也试过用官方的https://proxy.golang.org都不行

**Comment by tonycai653** [comment]
去掉代理拉取特定版本试试尼, 我这边测试go get github.com/qiniu/api.v7@v7.3.0没有问题的

**Comment by qiuchengw** [comment]
> 
> 
> 去掉代理拉取特定版本试试尼, 我这边测试go get github.com/qiniu/api.v7@v7.3.0没有问题的

你们到底自己试没试过 go mod形式去使用啊？到现在都不能用。

**Comment by bachue** [comment]
@qiuchengw 正确的 require 方式是 `require github.com/qiniu/api.v7/v7 v7.3.1`
