### ISSUE TITLE
为什么bytes和rpc的repo被删掉了

### ISSUE THREAD

**Issue by xingjy10** [qiniu/api.v7#175]
https://github.com/qiniu/api.v6/issues/141
api.v6里面有依赖bytes和rpc这两个repo.

**Comment by forrest-mao** [comment]
api.v7 相比 api.v6 有比较大的接口调整，一些依赖也存在变化，建议可以升级到 api.v7 的版本；
目前您具体是遇到了什么问题，是否可以帮忙描述下。

**Comment by xingjy10** [comment]
我们已经切到阿里云了，没用七牛了

**Comment by sheldon-lu** [comment]
../workspace/Goworkspace/pkg/mod/github.com/qiniu/api.v6@v6.0.9+incompatible/rs/rs_api.go:59:26: undefined: rpc.Logger


想问下有没有以前的rpc的repo或者留存下来的包？
