### ISSUE TITLE
go get -u github.com/qiniu/api.v7无法获取7.3.0版本

### ISSUE THREAD

**Issue by huhaifan** [qiniu/api.v7#176]
go get -u github.com/qiniu/api.v7无法获取7.3.0版本，go get -u github.com/qiniu/api.v7@master暂时可以解决

**Comment by huangjunwen** [comment]
同样问题

**Comment by bachue** [comment]
@huhaifan 未能重现，能否告知你的 Golang 版本，以及是否使用过镜像？

**Comment by wpxun** [comment]
我也遇到同样问题，go get -u github.com/qiniu/api.v7 默认不是 @latest 吗？怎么会拉取不到 tag:v7.3.0 呢，能解释一下吗?谢谢

**Comment by bachue** [comment]
@huangjunwen @huhaifan 已经修复 
@wpxun 主要是之前对于 go mod 的理解有点问题，现在已经修复了。你可以在一个使用了 go mod 的项目里，用 `go get -u -v github.com/qiniu/api.v7/v7` 的方式来获取 sdk。
