### ISSUE TITLE
接口说明，extra可以为空，可是为空时，就会崩掉 ，指针不对检测， if extra.UpHost != "" {

### ISSUE THREAD

**Issue by sybgo** [qiniu/api.v7#185]
// Put 用来以表单方式上传一个文件。
//
// ctx     是请求的上下文。
// ret     是上传成功后返回的数据。如果 uptoken 中没有设置 callbackUrl 或 returnBody，那么返回的数据结构是 PutRet 结构。
// uptoken 是由业务服务器颁发的上传凭证。
// key     是要上传的文件访问路径。比如："foo/bar.jpg"。注意我们建议 key 不要以 '/' 开头。另外，key 为空字符串是合法的。
// data    是文件内容的访问接口（io.Reader）。
// fsize   是要上传的文件大小。
// extra   是上传的一些可选项。可以指定为nil。详细见 PutExtra 结构的描述。
//
func (p *FormUploader) Put(
	ctx context.Context, ret interface{}, uptoken, key string, data io.Reader, size int64, extra *PutExtra) (err error) {
	err = p.put(ctx, ret, uptoken, key, true, data, size, extra, path.Base(key))
	return
}

func (p *FormUploader) put(
	ctx context.Context, ret interface{}, uptoken string,
	key string, hasKey bool, data io.Reader, size int64, extra *PutExtra, fileName string) (err error) {

	var upHost string
	if extra.UpHost != "" {
		upHost = extra.UpHost
	} else {

**Comment by forrest-mao** [comment]
内部issue ：TS-1005

**Comment by bachue** [comment]
这个 Issue 上一年就解决过了 https://github.com/qiniu/api.v7/pull/156
