### ISSUE TITLE
可否完善sms异常调用时的error返回值

### ISSUE THREAD

**Issue by br41n10** [qiniu/api.v7#194]
在使用sdk的sms模块发送短信时，碰到一个情况。
我的模板ID和签名ID写反了，这时拿到的sdk返回给我的error是
```
NotFoundError
```
但是从中看不出是什么造成了404。

在sdk里打了日志之后，发现七牛返回的http响应体是这样的
```json
{"error":"NotFoundError","message":"template(1177424*************) not found","request_id":"****************"}
```

然后就发现sdk是把响应体中的`error`字段返回了。但感觉把`message`字段一并带上更合适。

**Comment by forrest-mao** [comment]
感谢您的建议，我们来做跟进，内部issue ：TS-1006

**Comment by Mei-Zhao** [comment]
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
该issue会在go-sdk中解决
