### ISSUE TITLE
Header Host 不支持重设

### ISSUE THREAD

**Issue by yangwenmai** [qiniu/api.v7#216]
https://github.com/qiniu/api.v7/blob/master/storage/bucket.go#L302

不支持修改这个 Header Host。

但是 https://developer.qiniu.com/kodo/api/1250/batch 的 Host 是 rs.qbox.me

**Comment by forrest-mao** [comment]
batch 操作可以通过 storage.Config 来配置具体的 region，我们来看下补充相关的文档和 demo，内部 issue：TS-1008；
不过即使不修改 host，使用 rs.qbox.me 一般也不会影响具体的使用。
