### ISSUE TITLE
怎么获取桶里文件总数？

### ISSUE THREAD

**Issue by wleven** [qiniu/api.v7#221]
怎么获取桶里文件总数？

**Comment by forrest-mao** [comment]
文件数统计接口如下，不过目前确实还没有直接在 SDK 中实现，可能需要根据接口单独实现
标准存储文件数：https://developer.qiniu.com/kodo/api/3914/count
低频存储文件数：https://developer.qiniu.com/kodo/api/3915/count-line
归档存储文件数：https://developer.qiniu.com/kodo/api/6463/count-archive

**Comment by wleven** [comment]
ok 谢谢
