### ISSUE TITLE
调用bucketManager.FetchWithoutKey(resURL, bucket) 时候总是出现 504 Gateway Time-out

### ISSUE THREAD

**Issue by vasth** [qiniu/api.v7#224]
使用抓取网络资源到空间的时候我们用go sdk 
调用bucketManager.FetchWithoutKey(resURL, bucket) 时候总是出现 504 Gateway Time-out
有时候可以，有时候就不行

**Comment by bachue** [comment]
@vasth 同步抓取接口有可能因为资源下载的时候超时导致 API 超时，如果资源太大或网络连接不畅都有可能导致这一情况。建议使用 `AsyncFetch()` 异步抓取接口

**Comment by vasth** [comment]
谢谢你的回复，不过我还想再多问一下，这个AsyncFetch()接口我看返回的是一个AsyncFetchRet
type AsyncFetchRet struct {
	Id   string `json:"id"`
	Wait int    `json:"wait"`
}
我怎么通过这个AsyncFetchRet  获取到抓取文件的hash
看代码我的理解是这个是进行一个请求，但是请求成功不代表文件获取成功，是不是还需要在AsyncFetchParam中指定 回调的url，通过回调方法才能判断文件是否真正的上传成功了

**Comment by bachue** [comment]
@vasth 确实是这样的，API 文档在这里哈 https://developer.qiniu.com/kodo/api/4097/asynch-fetch
