### ISSUE TITLE
FileInfo 基本信息不全

### ISSUE THREAD

**Issue by yangwenmai** [qiniu/api.v7#239]
`https://github.com/qiniu/api.v7/blob/master/storage/bucket.go#L34`

FileInfo 基本信息不全，比方说文件状态（status）

参考文档：https://developer.qiniu.com/kodo/api/1308/stat

**Comment by forrest-mao** [comment]
感谢提醒，我们来 fix

**Comment by Mei-Zhao** [comment]
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
该issue会在go-sdk中解决
