### ISSUE TITLE
去掉代理拉取特定版本试试尼, 我这边测试go get github.com/qiniu/api.v7@v7.3.0没有问题的

### ISSUE THREAD

**Issue by AL4AL** [qiniu/api.v7#241]
去掉代理拉取特定版本试试尼, 我这边测试go get github.com/qiniu/api.v7@v7.3.0没有问题的

_Originally posted by @tonycai653 in https://github.com/qiniu/api.v7/issues/174#issuecomment-533967341_

**Comment by professorSajjad** [comment]
can anybody explains why this works?

**Comment by forrest-mao** [comment]
我们来确认下

**Comment by forrest-mao** [comment]
https://github.com/qiniu/api.v7/blob/v7.3.0/go.mod 这个应该是我们的 7.3.0 版本的 go.mod 书写有误，正确的应该是`module github.com/qiniu/api.v7/v7`，实在抱歉

**Comment by professorSajjad** [comment]
@forrest-mao 🙏🙏🙏

**Comment by Mei-Zhao** [comment]
该repo随后会设置为read-only，代码从 github.com/qiniu/api.v7 迁移至 github.com/qiniu/go-sdk。
该issue是已经发布历史版本bug，关闭该issue
