### ISSUE TITLE
can't download the pkg

### ISSUE THREAD

**Issue by jimwei** [qiniu/api.v7#25]
i use the command "go get -u qiniupkg.com/api.v7", but throw a error msg package qiniupkg.com/api.v7: unrecognized import path "qiniupkg.com/api.v7".
What should i do?

**Comment by longbai** [comment]
这个应该是没有正常访问qiniupkg.com 麻烦ping 下 qiniupkg.com，给个结果

**Comment by jimwei** [comment]
你好，无法ping通。提示错误信息如下：


Ping request could not find host qiniupkg.com. Please check the name and try again.


________________________________
发件人: Bai Long <notifications@github.com>
发送时间: 2015年9月17日 12:25
收件人: qiniu/api.v7
抄送: Wei YaPeng (Jim)
主题: Re: [api.v7] can't download the pkg (#25)


这个应该是没有正常访问qiniupkg.com 麻烦ping 下 qiniupkg.com，给个结果

―

**Comment by longbai** [comment]
看起来是域名解析问题， 麻烦将dns server 换成  114.114.114.114 或者其他的
