### ISSUE TITLE
有关于持久化处理（pfop）的api么？

### ISSUE THREAD

**Issue by daozhao** [qiniu/api.v7#27]
有关于持久化处理（pfop）的api么？
睇了一下文档，好像没有发现持久化处理（pfop）的api。还是我没有看清楚文档。请指教。

要直接写按照文档写http连接调用么？怎么go的api没有这个现成调用的。

**Comment by longbai** [comment]
这个先用url拼接好调用吧，目前go sdk还没有

**Comment by williambao** [comment]
@longbai 如何在go sdk中url拼接调用?
还是自行去处理[管理凭证]完全写一个http调用呢.
搞了两天一直不行, 管理凭证真的太难搞, 怎么换着写都显示 [bad token].
求一个在go 环境下调用音频处理的代码...
