### ISSUE TITLE
请问下 我用go sdk包生成上传uptoken 

### ISSUE THREAD

**Issue by guoxiangwen** [qiniu/api.v7#30]
请问下 我用go sdk包生成上传uptoken 在客户端用js-sdk凭借uptoken上传资源到七牛服务器 ，在哪里配置我的 两个KEY呢？还有bucketName？文档貌似没写清楚？

**Comment by tcmichael** [comment]
uptoken中Scope为bucket:key

**Comment by xushiwei** [comment]
@guoxiangwen 两个key是在服务端配置的，uptoken由服务端算好通过网络返回给客户端。bucketName 是在 uptoken 里面的 scope 字段。
