### ISSUE TITLE
kodo能否支持分块并行上传

### ISSUE THREAD

**Issue by robscc** [qiniu/api.v7#31]
kodo能否支持分块并行上传，
我们从国外服务器传国内的qiniu好像会比较慢 我想使用并行上传

**Comment by tcmichael** [comment]
sdk中RputFile是断点续传
或者查看文档
http://developer.qiniu.com/code/v6/api/kodo-api/up/mkblk.html
http://developer.qiniu.com/code/v6/api/kodo-api/up/bput.html
http://developer.qiniu.com/code/v6/api/kodo-api/up/mkfile.html
