### ISSUE TITLE
zones[1] 的地址有问题

### ISSUE THREAD

**Issue by fatboyzz** [qiniu/api.v7#35]
上传文件时如果使用 zones[1] 即 http://up-z1.qiniu.com 
会得到错误信息 incorrect zone, please use up-z0.qiniu.com

**Comment by tcmichael** [comment]
z1需要你的bucket 的空间属性是z1的才能使用，默认的bucket都是在z0, 这在下面我们推出多机房的方案时会详细描述。 目前也不对一般用户开放，想了解更多情况，请联系我们的技术支持。

**Comment by fatboyzz** [comment]
好的，谢谢。。。我先用着 z0 。
