### ISSUE TITLE
标准输出中会输出请求的信息

### ISSUE THREAD

**Issue by fatboyzz** [qiniu/api.v7#36]
具体位置在这里
rpc.v7/rpc_clieng.go:157 : PrettyPrintRequest(req)
应该去掉。。。

**Comment by tcmichael** [comment]
这个关于我们api的文档，这里没有rpc.v7的代码。事实上，我们最新的代码rpc.v7/rpc_clieng.go:157为reqC <- true，没有你所说的内容。

**Comment by fatboyzz** [comment]
囧，这是我很久以前自己加的代码。。。然后忘了。。。
