### ISSUE TITLE
两种方法生成出来的token不同

### ISSUE THREAD

**Issue by milkbobo** [qiniu/api.v7#46]
用linux命令：
echo "/v2/tune/refresh" |openssl dgst -binary -hmac "用户SK" -sha1 |base64 | tr + - | tr / _  
和用包的方法
mac := qbox.NewMac("AK", "SK")
sign := mac.Sign([]byte(data))
两个的生成出来的token不同，现在只能用第一种方法生成出来的token,第二种生成出来使用显示bad token.

**Comment by tcmichael** [comment]
根据文档http://developer.qiniu.com/article/developer/security/upload-token.html
token 由三个部分组成: uploadToken = AccessKey + ':' + encodedSign + ':' + encodedPutPolicy
用linux命令：
echo "/v2/tune/refresh" |openssl dgst -binary -hmac "用户SK" -sha1 |base64 | tr + - | tr / _
得到的结果 仅仅是encodedSign

用包的方法
mac := qbox.NewMac("AK", "SK")
sign := mac.Sign([]byte(data))
两个的生成出来的token不同，现在只能用第一种方法生成出来的token是三个部分的组合。

你说的第二种方法签名出来的中间那个部分和第一种方法生成的不同吗？

**Comment by milkbobo** [comment]
我是用缓存刷新那个生成token的
http://developer.qiniu.com/article/fusion/api/refresh.html#interface-address
我用上面链接中这种生成的 Authorization: QBox <用户AK>:<生成的token> 没问题的，但是我用mac.Sign([]byte("/v2/tune/refresh"))生成出来的token就不能用在缓存刷新的功能上

**Comment by longbai** [comment]
第一个貌似有回车

**Comment by milkbobo** [comment]
@longbai 当然有回车生成token出来 -_-

**Comment by tcmichael** [comment]
我们这里用包生成token是指针对的存储的：
mac := qbox.NewMac("AK", "SK")
sign := mac.Sign([]byte(data))
这个程序执行等效于：
echo -n "/v2/tune/refresh" |openssl dgst -binary -hmac "用户SK" -sha1 |base64 | tr + - | tr / _

而fusion的token的命令是：
echo "/v2/tune/refresh" |openssl dgst -binary -hmac "用户SK" -sha1 |base64 | tr + - | tr / _

他们的区别在于fusion的token，data多了一个\n字符。
你可以尝试在data最后添加一个\n字符来保持结果一样...

**Comment by milkbobo** [comment]
@tcmichael 请问我怎么样用包可以达到
echo "/v2/tune/refresh" |openssl dgst -binary -hmac "用户SK" -sha1 |base64 | tr + - | tr / _
这个效果呢？

**Comment by tcmichael** [comment]
前面回复了
sign := mac.Sign([]byte(data))
需要在data的最后加个\n的转义应该就行了，你可以试试。

**Comment by milkbobo** [comment]
用mac.Sign([]byte("/v2/tune/refresh\n"))生成的token比用命令行生成的token缺小一个字符。
原来是：mac.Sign方法里面是return mac.AccessKey + ":" + sign[:27]

**Comment by peaceful321** [comment]
可以提个工单，将两种方式生成的token 发一下，我们技术支持帮你来看一下；
