### ISSUE TITLE
无法为上传的文件指定路径前缀

### ISSUE THREAD

**Issue by 7sDream** [qiniu/api.v7#47]
![](http://7sdream-rikka-demo.daoapp.io/files/2016-09-11-968473482)

`uploader` 的 `Rput` 函数文档里写着 `key` 可以设定访问路径。

以下为我的代码：

![](http://7sdream-rikka-demo.daoapp.io/files/2016-09-11-198745420)

`ACCESSKEY` 和 `SECRETKEY` 皆已设置。 

但在我使用，如果上传的文件 `key` 加入了前缀 `rikka/`，则无法上传成功：

![](http://7sdream-rikka-demo.daoapp.io/files/2016-09-11-289987937)

上图里有很多我自己项目的 Log，所以可能有些难看清。但是注意第一个红框，`key` 是 `rikka/<uuid>`，然后二三两个框里就输出了上传重试/失败的消息。

如果 `key` 之前不加前缀 `rikka/` 则可上传成功：

![](http://od8qjnxw1.bkt.clouddn.com/f26d358e-0240-45b8-8c14-7569b7cbc8c6)

可以看到上传成功了，并且尝试访问最后的文件路径也能得到上传的文件。

所以我想问如果想要上传的时候设置路径，到底应该怎么使用 `key` 这个参数呢？难道需要 escape 么？

谢谢。

**Comment by 7sDream** [comment]
已找到问题，是编码上传的文件名中有非法字符，去掉了就好了。

**Comment by longbai** [comment]
👍  后面我们酌情增加一个文件名检查。
