### ISSUE TITLE
fail to go get qiniupkg.com/api.v7/api

### ISSUE THREAD

**Issue by fzhangtj** [qiniu/api.v7#62]
~$ go get qiniupkg.com/api.v7/api
package qiniupkg.com/api.v7/api: unrecognized import path "qiniupkg.com/api.v7/api" (parse https://qiniupkg.com/api.v7/api?go-get=1: no go-import meta tags)

**Comment by tcmichael** [comment]
go get -v 看看报什么错误
go get是golang提供的工具 给我们提issue并不能解决问题

**Comment by tcmichael** [comment]
go get -v 看看

**Comment by fzhangtj** [comment]
$ go get -v qiniupkg.com/api.v7/api
Fetching https://qiniupkg.com/api.v7/api?go-get=1
Parsing meta tags from https://qiniupkg.com/api.v7/api?go-get=1 (status code 404)
package qiniupkg.com/api.v7/api: unrecognized import path "qiniupkg.com/api.v7/api" (parse https://qiniupkg.com/api.v7/api?go-get=1: no go-import meta tags)

**Comment by tcmichael** [comment]
go get -v qiniupkg.com/api.v7 能执行吗？感觉不能到api.v7/api下面这层
实在不行就git clone吧 我这边感觉没有问题

**Comment by fzhangtj** [comment]
go get -v qiniupkg.com/api.v7 是可以的。是不是不能 go get qiniupkg.com/api.v7/api ，只能到qiniupkg.com/api.v7?

**Comment by tcmichael** [comment]
是的

**Comment by fzhangtj** [comment]
你好：

1. 感觉qiniupkg.com的返回结果有些问题.
命令 curl https://qiniupkg.com/api.v7 
结果:
\<head\>
\<meta name="go-import" content="qiniupkg.com/api.v7 git https://github.com/qiniu/api.v7"\>
\</head\>
\<body\>
\<p\>Hello, qiniupkg.com/api.v7!
\</body\>
\</html\>
命令 curl https://qiniupkg.com/api.v7/api
结果:
{"error":"Document not found"}
按照go 文档里(https://golang.org/cmd/go/#hdr-Remote_import_paths)说的，这个应该返回和https://qiniupkg.com/api.v7一样的结果，这样go get https://qiniupkg.com/api.v7/api就不会报错了。

1. go get  qiniupkg.com/api.v7/api应该成功才对，因为我们的代码里import的是qiniupkg.com/api.v7/api
