### ISSUE TITLE
地区选择 

### ISSUE THREAD

**Issue by LittleMonsterAK** [qiniu/api.v7#63]
能否像node的sdk一样自动添加一个地区选择的功能

**Comment by rwifeng** [comment]
golang的sdk中没有 地区选择进行了透明处理， 你不用关心地区的选择，sdk中直接进行了处理

**Comment by TianZong48** [comment]
bucket操作是需要选择区域的 [选择区域](https://github.com/qiniu/api.v7/blob/develop/kodo/doc.go#L10)
之后的操作不需要自己指定host，sdk会根据zone进行指定
@LittleMonsterAK
