### ISSUE TITLE
get domains for a bucket

### ISSUE THREAD

**Issue by piaoger** [qiniu/api.v7#64]
V7有没有类似于qshell domains bucket的功能？
qshell使用了V6来实现， 以后会使用v7来实现吗？

**Comment by tcmichael** [comment]
这个暂时还没有排期 我认为domains和bucket是一个相对固定的配置 可以放在服务端配置文件中。客户端应该不需要感知到。

**Comment by piaoger** [comment]
个人觉得应该还是比较重要的，我写了一工具通过bucket和key上传一个文件，按道理我应该知道这个信息就可以下载这个文件，但是现在不行，但是现在却必须再传入一个domain参数，感觉不对称，很丑陋

**Comment by jemygraw** [comment]
@piaoger 从哪个域名下载资源是需要额外分清楚的，比如从cdn域名和源站域名是分别不同的域名，即使是cdn，不同的资源也应该放在不同的加速平台，才能达到最佳的加速效果，所以如果仅仅是用于下载目的，需要手动指定需要的域名。

另外七牛的默认域名仅用于测试用途，一般不要放到线上使用。
