### ISSUE TITLE
初次尝试七牛云。请问按照文档创建的client 是否自动维护连接池？还是每次上传都需要重新创建一个？

### ISSUE THREAD

**Issue by wangfeiping** [qiniu/api.v7#71]
kodo.SetMac("", "")

zone := 1                // 您空间(Bucket)所在的区域: 华东 0，华北 1
c := kodo.New(zone, nil) // 用默认配置创建 Client

**Comment by tcmichael** [comment]
不需要每次上传都使用一个client golang的client自动维护连接池的

**Comment by rwifeng** [comment]
直接使用同一个client 即可。
