### ISSUE TITLE
Expose more interface

### ISSUE THREAD

**Issue by IamBusy** [qiniu/api.v7#73]
I propose exposing `bput` 、`mkblk` and `mkfile`  interface to coder to bring them more flexibility.
Though the possibility of  being called is small, it will be convenient for a coder to have the ability of calling them separately according to the situation. Since I am writing a storage driver based on qiniu for [docker/distribution](https://github.com/docker/distribution/), so I do think it not a good idea to   implement them again by myself due to the lack of interface above.

If needed, I can submit the pull requests.

**Comment by jemygraw** [comment]
yes, just go ahead
