### ISSUE TITLE
develop分支推送到 qiniupkg.com/api.v7 ？？

### ISSUE THREAD

**Issue by robscc** [qiniu/api.v7#76]
# qiniupkg.com/api.v7/kodo
../qiniupkg.com/api.v7/kodo/bucket.go:303: syntax error: unexpected URIDeleteAfterDays, expecting (

**Comment by robscc** [comment]
看上去改了，下次别这样啊...线上Docker构建用着用着就gg了

**Comment by jemygraw** [comment]
这个是merge的时候有个冲突，fixed in  89344a711feec1d800c77a80d0865de936dc394d
