### ISSUE TITLE
能出个版本吗

### ISSUE THREAD

**Issue by hyacinthus** [qiniu/api.v7#82]
各种包工具发现有版本，就会拉最后一个。但是那都是前年的了。

要么没版本，要么就不时的发布一下。

**Comment by jemygraw** [comment]
好的，最近在重构代码，不久就发布。

**Comment by hyacinthus** [comment]
醉了，master怎么比develop还领先了。 我锁定develop分支构建又报错了，过来一看更新了。。

**Comment by jemygraw** [comment]
发布 https://github.com/qiniu/api.v7/releases/tag/v7.2.0

**Comment by jemygraw** [comment]
这个版本改动比较大，建议参考下文档使用，这次重构将很多接口简单化了。
