### ISSUE TITLE
这两个包无法 get 下来? 

### ISSUE THREAD

**Issue by KISSMonX** [qiniu/api.v7#92]
$ go get qiniupkg.com/api.v7/kodocli
package qiniupkg.com/api.v7/kodocli: cannot find package "qiniupkg.com/api.v7/kodocli" in any of:

$ go get qiniupkg.com/api.v7/kodo
package qiniupkg.com/api.v7/kodo: cannot find package "qiniupkg.com/api.v7/kodo" in any of:

**Comment by jemygraw** [comment]
这个sdk已经更新了，客户删除本地的 api.v7 ，然后重新 `go get github.com/api.v7`

**Comment by KISSMonX** [comment]
kodo 和 kodocli 还是无法 get 下来. 已经删除不用了?

**Comment by jemygraw** [comment]
是的，新版本里面不需要这些了，可以参考最新的文档，重构之后结构更简单了。https://developer.qiniu.com/kodo/sdk/1238/go

**Comment by KISSMonX** [comment]
嗯嗯, 明白了, 我去看看文档, 刚接手一个遗留项目,  十分感谢.
