### ISSUE TITLE
用go get下载下来但是提示找不到这个包..我在git上边看代码也没有这个目录,,为什么呢

### ISSUE THREAD

**Issue by slidoooor** [qiniu/api.v7#97]
cannot find package "qiniupkg.com/api.v7/kodo" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/qiniupkg.com/api.v7/kodo (from $GOROOT)
	/Users/ch999/Documents/gopath/src/qiniupkg.com/api.v7/kodo (from $GOPATH)

**Comment by jemygraw** [comment]
目前sdk经过重构，删除了旧有的库引用方式，统一采用 github.com 引用方式，可以使用：

```
go get github.com/qiniu/api.v7
```

**Comment by slidoooor** [comment]
@jemygraw 我就是这么get的,,然后提示找不到..

**Comment by slidoooor** [comment]
@jemygraw 
go get -u github.com/qiniu/api.v7


# cd /Users/ch999/Documents/gopath/src/golang.org/x/net; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/net/context: exit status 1
很奇怪,,您知道是什么原因吗

**Comment by slidoooor** [comment]
@jemygraw 解决啦,麻烦你了

**Comment by JasonZhang1021** [comment]
我也想找这个包，qiniupkg.com/api.v7/kodo，没找到，想问下楼主怎么解决的呢？
